version: 0.2

phases:
  build:
    commands:
    - ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
    - REGION=us-east-1
    - ECR_REPO="swxsoc_sdc_aws_executor_lambda"
    - BASE_IMAGE=padre-swsoc-docker-lambda-base:latest
    - echo Login to Private ECR $REGION
    - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
    - echo ________________________________
    - |
      if git describe --tags --exact-match > /dev/null 2>&1; then
        echo "This is a tag push event"
        CDK_ENVIRONMENT=PRODUCTION
        BASE_IMAGE="public.ecr.aws/w5r9l1c8/$BASE_IMAGE"
        VERSION=`git describe --tags --exact-match`
      else
        echo "This is a production environment"
        ECR_REPO="$ECR_REPO"
        BASE_IMAGE="public.ecr.aws/w5r9l1c8/$BASE_IMAGE"
        CDK_ENVIRONMENT=PRODUCTION
        VERSION=`date -u +"%Y%m%d%H%M%S"`
      fi
    - echo ________________________________
    - echo Build Docker Image
    - FULL_ECR_REPO="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO"

    - docker build --build-arg BASE_IMAGE=$BASE_IMAGE -t $FULL_ECR_REPO:latest lambda_function/.
    - echo Tagging Docker Image...
    - docker tag $FULL_ECR_REPO:latest $FULL_ECR_REPO:$VERSION

    - echo Pushing the Docker image with Tags...
    - docker push $FULL_ECR_REPO:latest
    - docker push $FULL_ECR_REPO:$VERSION
    - echo ________________________________

    - echo Updating Deployment
    - echo ________________________________
    # - aws codebuild start-build --project-name arn:aws:codebuild:us-east-1:$ACCOUNT_ID:project/build_padre_sdc_aws_pipeline_architecture --environment-variables-override name=CDK_ENVIRONMENT,value=$CDK_ENVIRONMENT,type=PLAINTEXT

  post_build:
    commands:
      - echo Build Successful - Lambda Successfully Built and Pushed to ECR